# Generated by Django 3.2 on 2021-05-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondence', '0014_auto_20210512_1120'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('response_days', models.SmallIntegerField(default=15)),
                ('first_alert', models.SmallIntegerField(default=4)),
                ('second_alert', models.SmallIntegerField(default=9)),
                ('third_alert', models.SmallIntegerField(default=14)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='pqrs.type')),
            ],
        ),
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('radicate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondence.radicate')),
                ('data', models.TextField(max_length=2000)),
                ('response_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pqrs_response_mode', to='core.responsemode')),
                ('subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pqr_type', to='pqrs.subtype')),
            ],
            bases=('correspondence.radicate',),
        ),
    ]
