# Generated by Django 3.2 on 2021-05-12 11:20

import correspondence.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('correspondence', '0013_person_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsRetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_file_years', models.IntegerField(default=False)),
                ('gestion_file_years', models.IntegerField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retentions', to='core.office')),
            ],
        ),
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=64)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FilePhases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FinalDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RadicateTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Raft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=64)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_tvd', models.BooleanField()),
                ('cmis_id', models.TextField(max_length=128, null=True)),
                ('name', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('init_process_date', models.DateField()),
                ('init_date', models.DateField()),
                ('final_date', models.DateField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('final_disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondence.finaldisposition')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondence.filephases')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondence.processtype')),
                ('responsable', models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='record_responsable', to='core.userprofileinfo')),
                ('retention', models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='correspondence.docsretention')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=64)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('raft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subseries', to='correspondence.raft')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(max_length=64)),
                ('file', models.FileField(upload_to=correspondence.models.template_directory_path)),
                ('description', models.TextField(max_length=256)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.office')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_template_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_template_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='office',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='office',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='radicate',
            options={'ordering': ['date_radicated']},
        ),
        migrations.RemoveField(
            model_name='radicate',
            name='document_file',
        ),
        migrations.AddField(
            model_name='radicate',
            name='annexes',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='radicate',
            name='observation',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='radicate',
            name='office',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='radicates_office', to='core.office'),
        ),
        migrations.AddField(
            model_name='radicate',
            name='use_parent_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radicates_creator', to='core.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radicates_user', to='core.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='date_radicated',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='number',
            field=models.TextField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='person',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='radicates_person', to='core.person'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
        migrations.AddField(
            model_name='record',
            name='security_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondence.securitylevel'),
        ),
        migrations.AddField(
            model_name='record',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_record_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_record_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctype',
            name='sub_raft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_doc', to='correspondence.subraft'),
        ),
        migrations.AddField(
            model_name='docsretention',
            name='subraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retentions', to='correspondence.subraft'),
        ),
        migrations.AddField(
            model_name='radicate',
            name='doctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radicates_doctype', to='correspondence.doctype'),
        ),
        migrations.AddField(
            model_name='radicate',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radicates', to='correspondence.record'),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='reception_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondence.receptionmode'),
        ),
        migrations.AlterField(
            model_name='radicate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radicate_type', to='correspondence.radicatetypes'),
        ),
    ]
